[global]
   workgroup = WORKGROUP
   server string = SMB Test NAS
   security = user
   passdb backend = tdbsam
   log level = 1
   map to guest = bad user

[finance]
   path = /storage/finance
   valid users = @finance @executive
   read only = no
   browseable = yes
   create mask = 0660

[engineering]
   path = /storage/engineering
   valid users = @engineering @executive
   read only = no
   browseable = yes
   create mask = 0660

[hr]
   path = /storage/hr
   valid users = @hr @executive
   read only = no
   browseable = yes
   create mask = 0660
